CMakeLists.txt
Lets mpgen work without LD_LIBRARY_PATH in bitcoin depends builds
=> Set mpgen rpath

src/mp/util.cpp
Try to avoid massive debug log file sizes, and travis MemoryError in
https://github.com/bitcoin/bitcoin/pull/10102, https://travis-ci.org/bitcoin/bitcoin/jobs/558040257:
```
TestFramework (ERROR): Unexpected exception caught during testing
Traceback (most recent call last):
File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-unknown-linux-gnu/test/functional/test_framework/test_framework.py", line 193, in main
self.run_test()
File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-unknown-linux-gnu/test/functional/feature_block.py", line 1222, in run_test
self.send_blocks(blocks, True, timeout=1500)
File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-unknown-linux-gnu/test/functional/feature_block.py", line 1373, in send_blocks …
```
=> Limit LogEscape string size

CMakeLists.txt
Try to avoid errors on mac os which seems to use an older compiler by default
https://github.com/chaincodelabs/libmultiprocess/issues/5
=> Explicitly request C++14 compiler

include/mp/proxy-io.h, include/mp/proxy-types.h, include/mp/proxy.h, src/mp/test/test.cpp
Give ProxyClientBase class the ability to delete the Connection object in its destructor. This avoids the need for separate [`ShutdownLoop`](https://github.com/ryanofsky/bitcoin/blob/pr/ipc/src/interfaces/capnp/ipc.cpp#L50-L65) close hook in https://github.com/bitcoin/bitcoin/pull/10102.
This exposed a race condition which required adding a TaskSet member to Connection objects to fix. With the previous ShutdownLoop approach, the client capability handle would be freed in the event loop thread, then there would be a switch back to the client thread, then there would be another switch back to the event loop thread to free the connection, most likely after the event loop thread had a chance to process new events. With the new approach, the client capability handle and Connection object are …
=> Add ProxyClientBase destroy_connection option

include/mp/proxy-io.h, include/mp/util.h, src/mp/proxy.cpp, src/mp/util.cpp
Add forking and connecting functions to pull more IPC code out of https://github.com/bitcoin/bitcoin/pull/10102 into libmultiprocess
=> Add Connnect/Serve/Spawn/Wait functions

src/mp/util.cpp
Issue was found by hugohn in https://github.com/chaincodelabs/libmultiprocess/issues/5#issuecomment-518802181
=> Remove #include <syscall.h> to avoid mac os build error

include/mp/proxy-io.h, include/mp/proxy-types.h, include/mp/proxy.h, src/mp/proxy.cpp, src/mp/test/test.cpp
This is just cleanup. Using a pointer instead of reference used to be necessary
before the Connection constructor took a make_server option. But now there is
no reason to have a pointer and unnecessary null handling.
Also, Connection add_client option and AddClient RemoveClient ServeStream
wrapper functions are removed. These were originally meant to simplify usages
but cause more trouble than they are worth.
=> Replace ProxyServer connection pointer with reference

include/mp/proxy-io.h, src/mp/proxy.cpp
Useful to avoid having to use globals to pass information to custom ProxyClient,
ProxyServer overloads.
=> Add Eventloop void* context pointer

include/mp/proxy-io.h
Handles accepting connections from a listening socket and serving requests.
(Existing ServeStream function just serves requests on a single connection.)
=> Add ListenConnections function

include/mp/proxy-io.h, src/mp/gen.cpp, src/mp/proxy.cpp
A few changes that remove the usage of boost from some places in the code.
=> Reduce boost usage

include/mp/proxy-types.h
Refactor PassField() to an equivalent one that does not use
boost::optional.
=> Avoid using boost::optional in PassField()

src/mp/test/foo.h
std::string is used inside foo.h but it forgot to include the
corresponding header:
```
[ 53%] Building CXX object CMakeFiles/mptest.dir/src/mp/test/foo.capnp.proxy-server.c++.o
/usr/bin/c++   -I/usr/local/lib/cmake/CapnProto/../../../include -IBUILD/libmultiprocess/include -ISOURCE/libmultiprocess/include -ISOURCE/libmultiprocess/src -IBUILD/libmultiprocess/src -isystem /usr/local/include -D_THREAD_SAFE -pthread -std=gnu++14 -o CMakeFiles/mptest.dir/src/mp/test/foo.capnp.proxy-server.c++.o -c BUILD/libmultiprocess/src/mp/test/foo.capnp.proxy-server.c++
In file included from BUILD/libmultiprocess/src/mp/test/foo.capnp.proxy-server.c++:3:
In file included from BUILD/libmultiprocess/src/mp/test/foo.capnp.proxy-types.h:6:
In file included from …
```
=> Fix compilation of foo.h: include <string>

src/mp/gen.cpp, src/mp/util.cpp
Generate() and SpawnProcess() call fork(2) but did not check if it
failed (return -1) and continued execution with possible unexpected
results.
Handle fork(2) failure by throwing an exception.
=> Handle fork(2) failures

src/mp/util.cpp
This would make the error messages a bit more descriptive.
For example: `ex.what()` could be
`Invalid argument` before this patch and
`socketpair: Invalid argument` after this patch.
=> Tell std::system_error() which function failed

src/mp/util.cpp
Normally `ThreadName()` should return `programname-PID/threadname-TID`,
but if the thread name is not known it would return
`programname-PID/-TID`. Change it to return
`programname-PID/TID` instead.
=> Don't print a dash if thread name is not known

CMakeLists.txt, README.md, include/mp/proxy-io.h, include/mp/proxy-types.h, pkgconfig/libmultiprocess.pc.in
* While it may be possible to refactor the code in a way that it does
not use any `optional` types, like in a616312, fb73b81, 138ad67,
5724a2c, that would be error prone and would require bigger changes.
Switch from C++14 to C++17 instead and replace `boost::optional` with
`std::optional`.
* Removing `boost::current_exception_diagnostic_information()` - if the
caught exception is an instance of `std::exception`, use its `what()`
method. Otherwise don't provide extra diagnostic information. After
all `boost::current_exception_diagnostic_information()` would return
"No diagnostic information available." if it is not `std::exception`
or `boost::exception`.
* Clean up any mentions of Boost from README.md and CMakeLists.txt.
=> Obliterate Boost

include/mp/proxy-types.h, include/mp/util.h
Replace with ReadField wrapper and CustomReadField hook to be consistent with
BuildField / CustomBuildField. This
- Makes it more straightforward pass custom types with symmetric
CustomReadField / CustomBuildField overloads
- Simplifies debugging and overload resolution, removing hacks that allowed
ReadFieldNew calls to forward to ReadFieldUpdate calls and vice versa
- Enables more flexibility and efficiency within CustomReadField
implementations allowing emplacing or updating in the same function based on
which is simpler or more efficient. Removes a lot of std::enable_if overload
hacks
- Should allow clientInvoke to use RVO and construct return values in place
instead of copying or moving. This will allow more types to be for supported
as IPC return values even if they don't support …
=> Unify ReadFieldNew / ReadFieldUpdate

include/mp/util.h, src/mp/test/foo.capnp, src/mp/test/foo.h, src/mp/test/test.cpp
Also extend libmultiprocess unit test with coverage for this case.
Bad non-const ThrowFn declaration was causing ReadDestEmplace to try read
exception values after throwing them instead of before (in
update_fn(construct()) expression when construct() callback throws).
This was causing bitcoin functional tests to fail because JSONRPCError
exceptions caught were just null UniValue objects instead of objects with code
and message fields set.
=> Fix empty exception values from bad ThrowFn declaration

include/mp/proxy-io.h, include/mp/proxy-types.h, include/mp/proxy.h, src/mp/test/foo.capnp, src/mp/test/foo.h, src/mp/test/test.cpp
This is needed after https://github.com/bitcoin/bitcoin/pull/18338 which changed `handleNotifications()` `Notifications&` callback argument to `std::shared_ptr<Notifications>`.
Easiest way to support this was to change `ProxyServerBase` reference from a raw pointer to shared pointer and make necessary BuildField changes to pass along the `shared_ptr`. Alternative might have been to add more generic cleanup support to `ProxyServerBase` instead of hardcoding `shared_ptr`.
The change also required making the ReadField callback overload more generic, which was a straightforward but kind of big change that touched a lot of code.
There weren't any unit tests for callback support previously, so a lot of new test coverage was added. It includes coverage for `shared_ptr` lifetime correctness, …
=> Add shared_ptr callback support

src/mp/gen.cpp
Proxy client methods are usually virtual, but in some use cases (testing, layering) they don't have to have to be and there is no reason to make generated client code try to detect or specify this. Disable the warning instead.
Warnings look like https://cirrus-ci.com/task/6000489311502336?command=ci#L4294
```
./ipc/capnp/init.capnp.proxy.h:62:25: error: ‘virtual mp::FunctionTraits<std::unique_ptr<interfaces::Echo> (interfaces::Init::* const)()>::Result mp::ProxyClient<ipc::capnp::messages::Init>::makeEcho()’ can be marked override [-Werror=suggest-override]
62 |     typename M1::Result makeEcho();
|                         ^~~~~~~~
cc1plus: some warnings being treated as errors
```
=> Disable GCC suggest-override warnings for proxy clients

include/mp/proxy-types.h
CTransaction default constructor was removed in https://github.com/bitcoin/bitcoin/commit/faac31521bb7ecbf999541cf918d3750ff589de4 which exposed two places where libmultiprocess was inadvertently assuming default constructors were defined.
In both places, it would never actually call the default constructor at runtime, just rely on it being present during compile time code generation.
In the first case, compiler would fail while trying to figure out the type of `std::invoke_result_t<EmplaceFn>` where EmplaceFn called `make_shared<CTransaction>()`. This was fixed by just the moving expression into an unexpanded template method.
In the second case code was calling Optional<CTransaction>::emplace() to default-initialize CTransaction& output-arguments. It was fixed by moving into a …
=> Avoid depending on argument default constructors

include/mp/proxy-io.h, include/mp/proxy-types.h, include/mp/proxy.h, src/mp/gen.cpp, test/src/mp/test/test.cpp
This avoids the need to add interface base classes with `addCloseHook` methods in https://github.com/bitcoin/bitcoin/pull/19160 and https://github.com/bitcoin/bitcoin/pull/10102
=> Support attaching custom cleanup functions to proxy client and server classes

include/mp/proxy.capnp, src/mp/gen.cpp, test/src/mp/test/foo.capnp
Add Proxy include annotations for control over includes
=> Drop hardcoded #include lines in generated files

README.md, include/mp/proxy-io.h, src/mp/util.cpp
Just a few little changes made while reviewing. Feel free to discard or change any of the documentation edits.
=> Comments and LogEscape

src/mp/gen.cpp
Fix `make check` if previous incompatible version of libmultiprocess is installed and `make install` hasn't been run yet to update it.
Carl Dong reported this issue in https://github.com/chaincodelabs/libmultiprocess/issues/44 and confirmed the fix in https://github.com/chaincodelabs/libmultiprocess/issues/44#issuecomment-781658244
=> gen.cpp: Check local includes before install includes

CMakeLists.txt, README.md, example/CMakeLists.txt, example/calculator.capnp, example/calculator.cpp, example/calculator.h, example/example.cpp, example/init.capnp, example/init.h, example/printer.capnp, example/printer.cpp, example/printer.h
Added build instructions to README, but could use some more
documentation and CMakeLists.txt file could be made less repetitive
maybe introducing a mp_generate_cpp function that works like the
capnp_generate_cpp function.
=> Add standalone example with 3 processes

include/mp/proxy-types.h, src/mp/gen.cpp
Avoid and suppress various warnings reported in https://github.com/chaincodelabs/libmultiprocess/issues/61
=> Fix clang compiler warnings

CMakeLists.txt
Error looks like:
```
ld: ../libmultiprocess.a(proxy.cpp.o): in function `mp::EventLoop::EventLoop(char const*, std::function<void (bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)>, void*)':
libmultiprocess/src/mp/proxy.cpp:130: undefined reference to `kj::setupAsyncIo()'
collect2: error: ld returned 1 exit status
```
=> Fix mptest link error caused by missing kj-async dependency

include/mp/proxy-types.h, include/mp/proxy.h, include/mp/util.h, src/mp/gen.cpp
This is part of #46. `AUTORET` macro is no longer needed with C++14 `decltype(auto)`
=> cleanup: Remove AUTORET macro and clean up PassField overrides

src/mp/gen.cpp
Use clang __has_warning macro to avoid `unknown warning group '-Wsuggest-override'` warning in older versions of clang that have the `__has_warning` macro but don't have the `suggest-override` warning.
Errors were showing up https://github.com/bitcoin/bitcoin/pull/10102/checks?check_run_id=4671391974 / https://cirrus-ci.com/task/4642955743985664
=> Fix clang "unknown warning group" errors

CMakeLists.txt
Otherwise, the test always fails with "error: ‘uint64_t’ was not declared in this scope".
=> Fix check for `pthread_threadid_np`

CMakeLists.txt, example/CMakeLists.txt, test/CMakeLists.txt
It doesn't look robust to use different C++ standards for configuration and building.
This PR, for example, will apply the `-std=gnu++17` compiler option for all checks during configuration when building with GCC.
=> Use defined `CXX_STANDARD` for environment introspection

CMakeLists.txt
Instead of dependency `mpgen` on `multiprocess`, both of them can share the `util` object library.
This is a step towards ability to build and install `mpgen` and `multiprocess` independently, especially when [cross](https://github.com/bitcoin/bitcoin/pull/25941) building.
=> Make `mpgen` target independent from `multiprocess` one

CMakeLists.txt
No headers reside in the `${CMAKE_CURRENT_SOURCE_DIR}/src>` directory.
No changes in behavior.
=> Drop unneeded include directory

CMakeLists.txt
This PR adds new `install-lib` and `install-bin` build targets which allow to build and install only required artifacts during different stages of cross-building.
A demo, which uses this branch in Bitcoin Core, is [here](https://github.com/hebasto/bitcoin/commits/220907-mp-demo).
=> Add `install-lib` and `install-bin` build targets

include/mp/proxy-io.h
Fixes `-Wshadow-field` warning.
Closes #77.
=> refactor: Do not shadow `InvokeContext::connection` member

src/mp/gen.cpp
Also add comment to describe argument meanings.
Problem with string was reported by hebasto in https://github.com/chaincodelabs/libmultiprocess/pull/9#discussion_r973146130
=> doc: Fix mpgen usage string

CMakeLists.txt, cmake/capnp_compat.cmake
Two bugs configuring Cap'n Proto include directories were reported by sjors in https://github.com/chaincodelabs/libmultiprocess/issues/75
They appear to have gone undetected because they were masked in other contexts by `CMAKE_INCLUDE_PATH` and `NIX_CFLAGS_COMPILE` environment variable settings (https://github.com/chaincodelabs/libmultiprocess/issues/75#issuecomment-1262334271)
The first bug is missing `${CAPNP_INCLUDE_DIRECTORY}` target_include_directories in the `util` target. This resulted in a compile error `include/mp/util.h:8:10: fatal error: 'capnp/schema.h' file not found`
The second bug was misspelling `CAPNP_INCLUDE_DIRS` as `capnp_INCLUDE_DIRS` in the configure check for `kj/filesystem.h`, which caused `HAVE_KJ_FILESYSTEM` to be unset and could result in runtime errors like: …
=> build: Fix missing Cap'n Proto include directories

include/mp/proxy-types.h, test/mp/test/foo-types.h, test/mp/test/foo.capnp, test/mp/test/foo.h, test/mp/test/test.cpp
Add `RestDestTemp` function to simplify `ReadField` calls that just want to read a field into a new object.
Instead of requiring `ReadField` callers to construct the object in advance and pass it with `ReadDestValue`, or to write a custom emplace function and pass it with `ReadDestEmplace`, they can use `RestDestTemp` to make `ReadField` just construct a temporary object internally that can be moved from.
Add test coverage for this. Also add missing documentation comments for `ReadDestEmplace` and `ReadDestValue` classes.
=> Add ReadDestTemp function to make it easier to call ReadField with less boilerplate

CMakeLists.txt
This is a follow up of chaincodelabs/libmultiprocess#74 and addresses https://github.com/chaincodelabs/libmultiprocess/pull/74#pullrequestreview-1106150689:
> > The only downside of the current implementation is that new `install-lib` and `install-bin` targets do not export the underlying targets.
> 
> Can confirm neither of the new install commands create `$PREFIX/cmake/Multiprocess/Multiprocess.cmake` and `$PREFIX/lib/cmake/Multiprocess/Multiprocess-debug.cmake` files.
> 
> Probably should update `install()` `EXPORT Multiprocess` arguments to `EXPORT libmultiprocess-bin` and `EXPORT libmultiprocess-lib` so the two installs can be independent. And maybe there is a way to get the new `install-bin` and `install-lib` commands to actually export these targets.
=> Install Exports for custom `install-{lib,bin}` targets

example/calculator.cpp, example/example.cpp, example/printer.cpp, include/mp/proxy-types.h
Preemptively avoid clang-tidy errors before clang-tidy is introduced in https://github.com/chaincodelabs/libmultiprocess/pull/83. Other clang errors are already fixed in that PR, but these aren't maybe due to running different clang-tidy versions. The errors look like:
```c++
include/mp/proxy-types.h:162:85: warning: the parameter 'perhaps' is copied for each invocation but only used as a const reference; consider making it a const reference [performance-unnecessary-value-param]
.then([&server, invoke, req](kj::Maybe<Thread::Server&> perhaps) {
^
const                     &
example/printer.cpp:27:39: warning: the parameter 'message' is copied for each invocation but only used as a const reference; consider making it a const reference [performance-unnecessary-value-param]
void …
```
=> Avoid passing some function arguments by value

include/mp/proxy-types.h, test/mp/test/foo.capnp
When converting C++ std::pair and length 2 std::tuple values to and from capn'proto structs, no longer require the struct to have fields named "key" and "value".  Instead always map the first pair/tuple element to the first struct field, and the second element to the second field.
This allows anonymous std::pair and std::tuple types used in the C++ interface to have names and custom Read/Build logic when they are serialized as capn'proto messages.
For now only length-2 tuples are supported but this could be extended to support converting c++ tuples of arbitrary length to capn'proto structs with the same number of fields.
=> Remove naming requirement for std::pair/std::tuple

include/mp/proxy-types.h, test/mp/test/foo.capnp, test/mp/test/foo.h, test/mp/test/test.cpp
Needed to support `vector<bool>` `txout_is_change` field added in https://github.com/bitcoin-core/gui/pull/119
=> Add support for vector<bool> serialization

pkgconfig/libmultiprocess.pc.in
This compile flag was required previously when Bitcoin Core was using C++11, and libmultiprocess headers needed to be compiled with C++14 in order to be compatible with newer versions of Cap'n Proto. The flag was updated to C++17 since then.
But now Bitcoin Core has been updated to use C++20 and having the C++17 flag causes errors when the std::u8string type is referenced in bitcoin code. So just remove the C++ flag and let the application be responsible for choosing the C++ version.
=> pkgconfig: Drop -std=c++17 compile flag

pkgconfig/libmultiprocess.pc.in
Use @CMAKE_INSTALL_LIBDIR@ variable instead of hardcoding "lib" as the libdir. This is needed after 54bd57fb3b064c7f3d556b015e8f64fd8d234c19 (https://github.com/chaincodelabs/libmultiprocess/pull/79) which changed the installation to sometimes install to "lib64".
This fixes error "ld: cannot find -lmultiprocess: No such file or directory" in Bitcoin Core.
Also replace hardcoded "include" with @CMAKE_INSTALL_INCLUDEDIR@ for consistency.
=> pkgconfig: Use @CMAKE_INSTALL_LIBDIR@ variable

include/mp/proxy-types.h
The vector<bool> serialization supported added in https://github.com/chaincodelabs/libmultiprocess/pull/86 commit 1c6fb04dddfc0de35eb5952649fda83a030ff288 was only tested with libstdc++ not libc++ and caused a test compilation failure when compiling on macos, reported by edilmedeiros in https://github.com/chaincodelabs/libmultiprocess/issues/92
Fix the issue that was causing the build to fail: trying to use using vector's reference type instead of const_reference type when serializing the vector.
Fixes #92
=> Fix support for vector<bool> serialization with libc++

CMakeLists.txt, cmake/LibmultiprocessMacros.cmake, example/CMakeLists.txt, test/CMakeLists.txt
This PR introduces the `LibmultiprocessMacros` module that is used internally and might be exported as a part of the (future) `LibmultiprocessGen` package (it is a subject of the follow-up [PR](https://github.com/chaincodelabs/libmultiprocess/pull/96)).
Also see a discussion in https://github.com/hebasto/bitcoin/pull/118.
=> cmake: Introduce `LibmultiprocessMacros` module

CMakeLists.txt, cmake/LibmultiprocessConfig.cmake.in, cmake/LibmultiprocessGenConfig.cmake.in, cmake/LibmultiprocessMacros.cmake, example/CMakeLists.txt, test/CMakeLists.txt
This PR adds configurations for the `Libmultiprocess` and `LibmultiprocessGen` packages.
The Bitcoin Core branch, with uses this PR branch, is available [here](https://github.com/hebasto/bitcoin/tree/240329-cmake-CI-mpgen).
As a suggestion for a follow-up, it seems worth disabling `mpgen` target for cross-compiling (see https://github.com/bitcoin/bitcoin/pull/29665#issuecomment-2002027957 and CMake [docs](https://cmake.org/cmake/help/book/mastering-cmake/chapter/Cross%20Compiling%20With%20CMake.html#running-executables-built-in-the-project)).
Based on https://github.com/chaincodelabs/libmultiprocess/pull/95.
=> cmake: Introduce packages

CMakeLists.txt, cmake/Config.cmake.in, cmake/LibmultiprocessBinConfig.cmake.in, cmake/LibmultiprocessLibConfig.cmake.in, cmake/pthread_checks.cmake, doc/install.md
This change combines previous installed:
- `cmake/LibmultiprocessLibConfig.cmake`
- `cmake/LibmultiprocessBinConfig.cmake`
files into a single:
- `cmake/Libmultiprocess/LibmultiprocessConfig.cmake`
file, so it can be imported with `find_package(Libmultiprocess)`.
The previous locations which were set in https://github.com/chaincodelabs/libmultiprocess/pull/97 were not compatible with `find_package` search behavior by default.
The change also adds some documentation about using the new package to doc/install.md.
=> cmake: Combine installed packages

src/mp/proxy.cpp
Run Connection class asynchronous cleanups in LIFO not FIFO order, which is more natural ordering and prevents a bitcoin wallet shutdown deadlock when the connection to the node process is broken. Also add comments better documenting cleanup order.
This change fixes one of two shutdown deadlocks in the bitcoin wallet when the node process is killed in https://github.com/bitcoin/bitcoin/pull/10102 as of https://github.com/bitcoin/bitcoin/commit/3f12b4362c1b822835889151f6cd54c4829cf3ad. The other deadlock is caused by the `ProxyServerCustom<WalletLoader>` destructor in that PR and is described in commit efe42cc2879915b2ffdff04ec1cfe715e8dfa0a0 from #100.
The bitcoin wallet shutdown deadlocks have probably been around for some time, but were not encountered because before …
=> connection: run async cleanups in LIFO not FIFO order

include/mp/proxy-io.h, include/mp/proxy-types.h
Improve comments describing proxy server and proxy client object shutdown sequences.
This also adds a new assert in ~ProxyServerBase()
=> doc: Document shutdown sequences better

cmake/Config.cmake.in
When loading a package configuration file, `find_package` defines variables to provide information about the call arguments. In particular, `CMAKE_FIND_PACKAGE_NAME` represents the package name.
This PR uses this variable instead of a hardcoded name, making the use case suggested in https://github.com/chaincodelabs/libmultiprocess/pull/98#issuecomment-2243751206 workable:
```cmake
find_package(Libmultiprocess COMPONENTS Lib)
find_package(LibmultiprocessNative COMPONENTS Bin
NAMES Libmultiprocess
)
```
=> cmake: Fix package configuration file

include/mp/proxy-types.h, test/mp/test/foo.capnp, test/mp/test/foo.h, test/mp/test/test.cpp
Trying to pass an empty struct that is annotated with `$Proxy.wrap`  and has no data fields fails because the `BuildOne` overload for the last field number is incorrectly declared to accept an lvalue builder reference instead of a universal reference, and the `CustomBuildField` overload which calls `BuildOne` passes an `rvalue` builder, so the call fails with error:
```c++
include/mp/proxy-types.h:1066:5: error: no matching function for call to 'BuildOne'
1066 |     BuildOne<0>(local_type, invoke_context, output.init(), value);
include/mp/proxy-types.h:1050:6: note: candidate function [with index = 0, LocalType = mp::test::FooEmpty, Value = mp::test::FooEmpty, Output = mp::test::messages::FooEmpty::Builder] not viable: expects an lvalue for 3rd argument
1050 | void …
```
=> Fix $Proxy.wrap mapping for empty structs with no fields

include/mp/proxy-types.h, test/mp/test/foo-types.h, test/mp/test/foo.capnp, test/mp/test/foo.h, test/mp/test/test.cpp
Add `CustomBuildMessage`, `CustomReadMessage`, and `CustomPassMessage` hook functions. These functions can be defined to use custom code to convert C++ objects to and from Cap'n Proto messages. They work similarly to existing `CustomBuildField`, `CustomReadField,` and `CustomPassField` hooks, except they can be defined as normal functions not template functions, so they should be easier to use and require less verbosity in most cases, although they are less flexible.
The unit tests added here are new but the feature was originally implemented in https://github.com/bitcoin/bitcoin/pull/10102 but and is being ported because it's a general purpose feature.
=> types: Add Custom{Build,Read,Pass}Message hooks

include/mp/proxy-io.h, include/mp/proxy-types.h, src/mp/proxy.cpp
Currently ThreadContext Connection* pointers are not removed up when a connection is destroyed. This is only a problem if a Connection instance is destroyed and new Connection is allocated at the same address, because the code assumes pointers uniquely identify connections. This causes a bug in a bitcoin IPC test which creates multiple connections in a loop, described in https://github.com/bitcoin/bitcoin/pull/30509#issuecomment-2276739868, and depending on how the heap allocator behaves, a new Connection could have the same address as a previously destroyed connection, and the code tries to use a thread reference associated with the previous connection when making a new call, and there is a segfault because the thread no longer exists.
Fix this problem by adding Connection cleanup …
=> Bugfix: Clean up ThreadContext pointers when Connection is destroyed

example/example.cpp
Problem was pointed out by TheCharlatan in https://github.com/chaincodelabs/libmultiprocess/pull/107#issuecomment-2301338227
=> example: Add missing thread.join() call so example can exit cleanly

cmake/TargetCapnpSources.cmake
Modify target_capnp_sources function to create a custom cmake target depending on generated capnp headers, that can be listed as an explicit dependency of other c++ targets when cmake's implicit dependency tracking for included files doesn't work.
This might help fix the build problem encountered https://github.com/bitcoin/bitcoin/pull/30510#issuecomment-2334799124
=> cmake: add target_capnp_sources headers target

include/mp/proxy-io.h, src/mp/proxy.cpp, test/mp/test/test.cpp
=> shutdown bugfix: destroy RPC system before running cleanup callbacks

CMakeLists.txt, cmake/compat_config.cmake, cmake/compat_find.cmake
Add workaround to prevent "libatomic not found" when building on debian against debian capnproto package which installs a buggy CapnProtoConfig.cmake file. The bug was introduced as part of debian's attempt to fix a different issue: https://github.com/capnproto/capnproto/issues/1448 and their fix works for autoconf projects but not cmake projects like libmultiprocess.
Fixes #68
=> cmake: avoid libatomic not found error on debian

include/mp/proxy-io.h, src/mp/gen.cpp
`ProxyClientBase` constructor was trying to call `ProxyClient::construct()` method before `ProxyClient` object had been fully constructed. This is causing a UBSAN error reported:
- https://github.com/bitcoin/bitcoin/pull/30975#issuecomment-2511204009
- https://github.com/bitcoin/bitcoin/actions/runs/11970857809/job/33374462331?pr=30975
that looks like:
```c++
include/mp/proxy.h:95:45: runtime error: downcast of address 0x50600002bdc0 which does not point to an object of type 'ProxyClient<Interface>' (aka 'ProxyClient<ipc::capnp::messages::Init>')
0x50600002bdc0: note: object is of type 'mp::ProxyClientBase<ipc::capnp::messages::Init, interfaces::Init>'
```
=> ProxyClientBase: avoid static_cast to partially constructed object

include/mp/proxy-types.h, test/mp/test/foo.capnp, test/mp/test/foo.h
Add static_assert to detect when an int field is too small to hold an enum value
This catches the bug TheCharlatan pointed out in https://github.com/bitcoin/bitcoin/pull/29409#discussion_r1834362068
=> proxy-types.h: add static_assert to detect int/enum size mismatch

include/mp/proxy-io.h, include/mp/proxy.h, src/mp/gen.cpp
This is a bugfix that should fix the UBSan failure reported https://github.com/chaincodelabs/libmultiprocess/issues/125
In practice there is no real bug here, just like there was no real bug fixed in the recent "ProxyClientBase: avoid static_cast to partially constructed object" change in https://github.com/chaincodelabs/libmultiprocess/pull/121. This is because in practice, ProxyClient subclasses only inherit ProxyClientBase state and do not define any state of their own, so there is nothing bad that could actually happen from static_cast-ing a ProxyClientBase pointer to a ProxyClient pointer inside the ProxyClientBase constructor or destructor.
However, using static_cast this way technically triggers undefined behavior, and that causes UBSan to fail, so this commit drops the static_cast …
=> ProxyClientBase: avoid static_cast to partially destructed object

include/mp/proxy-io.h, src/mp/proxy.cpp
The EventLoop shutdown sequence has race conditions that could cause it to shut down right before a `removeClient` `write(m_post_fd, ...)` call is about to happen, if threads run in an unexpected order, and cause the write to fail.
Cases where this can happen are described in https://github.com/bitcoin/bitcoin/issues/31151#issuecomment-2609686156 and the possible causes are that (1) `EventLoop::m_mutex` is not used to protect some EventLoop member variables that are accessed from multiple threads, particularly (`m_num_clients` and  `m_async_fns`) and (2) the `removeClient` method can do unnecessary `write(m_post_fd, ...)` calls before the loop is supposed to exit because it is not checking the `m_async_fns.empty()` condition, and these multiple write calls can make the event loop exit …
=> Fix "disconnected: write(m_post_fd, &buffer, 1): Broken pipe" EventLoop shutdown races.

include/mp/proxy-io.h, include/mp/proxy.h, src/mp/proxy.cpp, test/mp/test/test.cpp
Add CleanupRun function to dedup clean list code. Also rename "cleanup" variables to distinguish between cleanup iterators and cleanup callback functions.
These changes were originally part of https://github.com/chaincodelabs/libmultiprocess/pull/126 which was closed for other reasons, but I think they are still helpful and make code easier to navigate.
Since this renames a public struct member, it will require a change to bitcoin core when the depends version is bumped:
```c++
diff --git a/src/ipc/capnp/protocol.cpp b/src/ipc/capnp/protocol.cpp
index 4b67a5bd1e36..691bdf5f9242 100644
--- a/src/ipc/capnp/protocol.cpp
+++ b/src/ipc/capnp/protocol.cpp
@@ -73,7 +73,7 @@ public:
}
void addCleanup(std::type_index type, void* iface, std::function<void()> cleanup) override
{
- …
```
=> refactor: Add CleanupRun function to dedup clean list code

include/mp/proxy-io.h
While implementing #129 I noticed startAsyncThread comment wasn't totally accurate so this should fix that.
=> doc: fix startAsyncThread comment

cmake/Config.cmake.in
This is an extension of the workaround implemented previously in #119. That workaround let the libmultiprocess cmake build work with the debian capnproto package.
This change extends the workaround to apply to downstream cmake builds that call find_package(Libmultiprocess), like Bitcoin Core.
Fixes #132
=> Fix debian "libatomic not found" error in downstream builds

include/mp/proxy-io.h, include/mp/proxy-types.h, include/mp/util.h
There should be a lot of places where new C++ features can be used to simplify code, particularly concept features in C++20 so I'm starting to go through code and look for places where it can be modernized. Will collect the smaller cleanups in this PR and probably open other PRs with bigger cleanups.
=> c++ 20 cleanups

doc/usage.md
Detected by downstream ci https://cirrus-ci.com/task/6241220336287744?logs=lint#L459 in https://corecheck.dev/bitcoin/bitcoin/pulls/31741
=> doc: Fix broken markdown links

CMakeLists.txt
This allows a vendored libmultiprocess to inherit the c++ version from the main project
=> build: don't clobber user/superproject c++ version

CMakeLists.txt, cmake/TargetCapnpSources.cmake
The parent project or user can supply `EXTERNAL_MPGEN`, which will override the one set here. If not set, the internally built one is used instead.
This is useful for cross builds, especially when using libmultiprocess as a subdirectory. Parent projects can similarly define a cache var.
Note that the internal binary is still built, but it can be skipped by building the multiprocess target directly.
This is the simplest impl of this I could come up with. Trying to pass an optional option for the binary into `target_capnp_sources` is not very ergonomic with CMake, so I've opted for just using a global here instead.
It would probably make sense to disable the internal mpgen target if the external option is used, but that adds a good bit of complexity, so I haven't done it here. Happy to do …
=> build: add option for external mpgen binary

src/mp/proxy.cpp
This legitimate warning pops up when built with clang 20 and Core's flags:
`warning: field 'm_context' will be initialized after field 'm_task_set' [-Wreorder-ctor]`
It looks like there are no dependency issues here and the reordering is safe, but please let me know if I'm wrong.
=> cleanup: initialize vars in the EventLoop constructor in the correct order

CMakeLists.txt
Tweak `target_link_libraries` calls to correctly declare dependencies on capnproto libraries as public, so capnproto include directories get correctly added to downstream targets. Without this, compiler warnings can be triggered from capnproto headers because they are not treated like external headers.
Fixes https://github.com/chaincodelabs/libmultiprocess/issues/138
This should be an alternative to #141
=> cmake: Suppress compiler warnings from capnproto headers

src/mp/util.cpp
/ci_container_base/src/ipc/libmultiprocess/src/mp/util.cpp:74:12: error: moving a temporary object prevents copy elision [-Werror,-Wpessimizing-move]
74 |     return std::move(buffer.str());
|            ^
/ci_container_base/src/ipc/libmultiprocess/src/mp/util.cpp:74:12: note: remove std::move call here
74 |     return std::move(buffer.str());
|            ^~~~~~~~~~            ~
=> util: fix -Wpessimizing-move warning

CMakeLists.txt, test/CMakeLists.txt
In order to be able to run `ctest` from the top level build directory, it is necessary that `enable_testing()` is invoked in the top level CMakeLists.txt file. The `CTest` module invokes `enable_testing()` based on the value of `BUILD_TESTING`.
=> CTest: Module must be included at the top level

src/mp/util.cpp
Fixes https://github.com/bitcoin/bitcoin/pull/30975#issuecomment-2633222863:
> On my own macOS 15.3 with Xcode 16.2 machine building fails:
> 
> ```
> git clean -dfx
> cmake -B build -DENABLE_IPC=ON
> cmake --build build
> ...
> /Users/sjors/dev/bitcoin/src/ipc/libmultiprocess/src/mp/util.cpp:22:5: error: '__linux__' is not defined, evaluates to 0 [-Werror,-Wundef]
>    22 | #if __linux__
>       |     ^
> /Users/sjors/dev/bitcoin/src/ipc/libmultiprocess/src/mp/util.cpp:62:5: error: '__linux__' is not defined, evaluates to 0 [-Werror,-Wundef]
>    62 | #if __linux__
>       |     ^
> 2 errors generated.
> ```
=> Avoid `-Wundef` compiler warnings

CMakeLists.txt, example/calculator.cpp, example/example.cpp, example/printer.cpp, src/mp/gen.cpp, src/mp/util.cpp, test/mp/test/test.cpp
Changes suggested in https://github.com/bitcoin/bitcoin/pull/31741#discussion_r1942612485 to be able to enable more linters in Bitcoin Core CI.
=> refactor: Remove locale-dependent function calls

example/example.cpp, src/mp/util.cpp
Partially revert #156 due to lack of compiler support for std::format, as reported https://github.com/chaincodelabs/libmultiprocess/pull/156#issuecomment-2643476222 and https://github.com/bitcoin/bitcoin/pull/31741#issuecomment-2643619428
Technically it means this code is using locale dependent functions again, though I think in practice results will not be locale dependent because these are just integers not floating point numbers being formatted.
This code could be written to use std::to_chars and be more independent, at the cost being slightly more complicated. Could be considered for a followup.
=> refactor: Avoid using std::format

include/mp/proxy-io.h, src/mp/proxy.cpp
Currently, there are two cases where code may attempt to lock `EventLoop::mutex` after the `EventLoop::loop()` method has finished running. This is not a problem by itself, but is a problem if there is external code which deletes the `EventLoop` object immediately after the method returns, which is the case in Bitcoin Core. Both cases of locking after the loop method returns happen due to uses of the `Unlock()` utility function which unlocks a mutex temporarily, runs a callback function and relocks it.
The first case happens in `EventLoop::removeClient` when the `EventLoop::done()` condition is reached and it calls `Unlock()` in order to be able to call `write(post_fd, ...)` without blocking and wake the EventLoop thread. In this case, since `EventLoop` execution is done there is not …
=> bugfix: Do not lock EventLoop::mutex after EventLoop is done

CMakeLists.txt
Avoid including CTest in if this is not a top-level cmake project because as reported https://github.com/chaincodelabs/libmultiprocess/pull/145#issuecomment-2644563297 this adds a `BUILD_TESTING` option could be confused for Bitcoin core's `BUILD_TESTS` option.
=> cmake: Avoid including CTest if not top level project

CMakeLists.txt, cmake/TargetCapnpSources.cmake
This PR automates handling of `MP_INCLUDE_DIR` in the `target_capnp_sources` function, removing the need to manually propagate it across directories for both this project and downstream projects.
=> Switch `MP_INCLUDE_DIR` to global property

ci/configs/llvm.bash, ci/configs/sanitize.bash, include/mp/proxy-io.h, include/mp/proxy-types.h, include/mp/type-context.h, include/mp/util.h, src/mp/proxy.cpp
This bug is currently causing mptest "disconnecting and blocking" test to occasionally hang as reported by maflcko in https://github.com/bitcoin/bitcoin/issues/33244.
The bug was actually first reported by Sjors in https://github.com/Sjors/bitcoin/pull/90#issuecomment-3024942087 and there are more details about it in https://github.com/bitcoin-core/libmultiprocess/issues/189.
The bug is caused by the "disconnecting and blocking" test triggering a disconnect right before a server IPC call returns. This results in a race between the IPC server thread and the `onDisconnect` handler in the event loop thread both trying to destroy the server's `request_threads` `ProxyClient<Thread>` object when the IPC call is done.
There was a lack of synchronization in this case, fixed here by adding …
=> bug: fix mptest hang, ProxyClient<Thread> deadlock in disconnect handler

include/mp/proxy-io.h, include/mp/type-context.h, test/mp/test/test.cpp
Relevant Issue: https://github.com/bitcoin-core/libmultiprocess/issues/206
This error occurs when non-C++ clients make simultaneous IPC calls to the server using the same Server thread.  
The libmultiprocess C++ client ensures a 1-to-1 mapping of client-to-server threads, so simultaneous calls using the same thread cannot be made.
---
I have added a unit test in the last commit.
You can cherry-pick this commit on master to reproduce the crash.
=> Fix crash on simultaneous IPC calls using the same thread

test/mp/test/foo.capnp, test/mp/test/foo.h, test/mp/test/test.cpp
This PR adds two test cases to ensure that output parameter results from a server call are correctly captured and included in the response.
The new tests also serve as practical examples of how to work with output parameters and `in|out` parameters in the codebase.
Automated coverage is not yet available, see https://github.com/bitcoin-core/libmultiprocess/issues/198.
As a temporary verification method:
- Comment out [these lines](https://github.com/bitcoin-core/libmultiprocess/blob/47d79db8a5528097b408e18f7b0bae11a6702d26/include/mp/proxy-types.h#L308-L310)
and run make check. The new test should fail, confirming it is effective.
- If you then also comment out the newly added tests and rerun make check, it should pass, demonstrating that the lines above were previously uncovered.
=> test default PassField impl handles output parameters
